env:
  - PYVER="3.6"

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran graphviz
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

install:
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda env create -q -f binder/environment.yml
  - source activate math-python
  - python -m ipykernel install --user --name math-python --display-name "Python (math-python)"
  - echo "options(repos = c(CRAN='https://mran.microsoft.com/snapshot/2018-05-02'), download.file.method= 'libcurl')" > ~/.Rprofile
  - Rscript binder/install.R

script: 
  - ipython -c "%run notebooks_2017/00.Installation.py"
  - ipython -c "%run notebooks_2017/01.Introduction.py"
  - ipython -c "%run notebooks_2017/02.Strings.py"
  - ipython -c "%run notebooks_2017/03.Lists.py"
  - ipython -c "%run notebooks_2017/04.Control.Flow.Tools.py"
  - ipython -c "%run notebooks_2017/05.Modules.py"
  - ipython -c "%run notebooks_2017/06.Input.And.Output.py"
  - ipython -c "%run notebooks_2017/07.Errors.and.Exceptions.py"
  - ipython -c "%run notebooks_2017/08.Classes.py"
  - ipython -c "%run notebooks_2017/09.Iterators.py"
  - ipython -c "%run notebooks_2017/10.Multiprocessing.py"
  - ipython -c "%run notebooks_2017/11.Standard.Library.py"
  - ipython -c "%run notebooks_2017/12.Matplotlib.py"
  - ipython -c "%run notebooks_2017/13.Numpy.py"
  - ipython -c "%run notebooks_2017/14.SciPy.py"
  - ipython -c "%run notebooks_2017/15.Sympy.py"
  - ipython -c "%run notebooks_2017/16.Dask.py"
  - ipython -c "%run notebooks_2017/17.InteractiveWidgets.py"
  - ipython -c "%run notebooks_2017/18.Pandas.Series.py"
  - ipython -c "%run notebooks_2017/19.Pandas.DataFrame.py"
  - ipython -c "%run notebooks_2017/20.IRMAR.py"
  - ipython -c "%run notebooks_2017/21.Pandas.Exercises.py"
  - ipython -c "%run notebooks_2017/22.GeoGebra.Day.py"
  - ipython -c "%run notebooks_2017/23.Julia.Set.py"
  - ipython -c "%run notebooks_2017/24.DaskDataframes.py"
  - ipython -c "%run notebooks_2017/25.Seaborn.py"
  - ipython -c "%run notebooks_2017/26.NBA.Games.py"
  - ipython -c "%run notebooks_2018/01.CaesarCipher.py"
  - ipython -c "%run notebooks_2018/02.Polynomial.py"
  - ipython -c "%run notebooks_2018/03.GrayScott.py"
