name: math-python
channels:
  - damianavila82
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - jupyter_contrib_nbextensions
  - lorem 
  - rise
  - autopep8
  - joblib
  - matplotlib
  - scipy
  - numpy
  - pandas
  - seaborn
  - dataclasses
