name: math-python
channels:
  - conda-forge
  - r
  - defaults
dependencies:
  - python=3.6
  - autopep8
  - beautifulsoup4
  - cloudpickle
  - cython
  - dask
  - dataclasses
  - fortran-magic
  - graphviz
  - h5py
  - ipywidgets
  - joblib
  - jupyter
  - jupyterlab
  - lorem 
  - lxml
  - matplotlib
  - memory_profiler
  - numba
  - numpy
  - pandas
  - pytables
  - python-graphviz
  - pytest
  - pythran
  - r
  - r-nloptr
  - r-tidyverse
  - r-irkernel
  - rpy2
  - scipy
  - seaborn
  - sympy
  - toolz
  - tzlocal
  - xlwt
  - line_profiler
