name: math-python
channels:
  - sympy
  - conda-forge
  - defaults
dependencies:
  - lorem 
  - autopep8
  - joblib
  - matplotlib
  - scipy
  - numpy
  - pandas
  - seaborn
  - dataclasses
  - sympy
  - dask
  - tzlocal
  - rpy2
  - xlwt
  - pytables
  - toolz
  - cloudpickle
  - graphviz
  - cython
  - memory_profiler
  - fortran-magic
  - numba
  - ipywidgets
